import { useState } from "react";
import { useTranslation } from "react-i18next";
import type { ConsultationResult } from "@/types";

interface ShareButtonProps {
  result: ConsultationResult;
}

function generateShareText(result: ConsultationResult): string {
  const lines: string[] = ["NPS Oracle Reading", ""];

  switch (result.type) {
    case "reading": {
      const d = result.data;
      lines.push(
        `Date: ${d.generated_at ? new Date(d.generated_at).toLocaleDateString() : "N/A"}`,
      );
      lines.push("Type: Time Reading");
      lines.push("");
      lines.push(d.summary);
      lines.push("");
      if (d.numerology) {
        lines.push(`Life Path: ${d.numerology.life_path}`);
      }
      if (d.fc60) {
        lines.push(
          `Element: ${d.fc60.element} | Energy: ${d.fc60.energy_level}`,
        );
      }
      if (d.moon) {
        lines.push(`Moon: ${d.moon.emoji} ${d.moon.phase_name}`);
      }
      break;
    }
    case "question": {
      const d = result.data;
      lines.push("Type: Question Reading");
      lines.push("");
      lines.push(`Question: ${d.question}`);
      lines.push(`Number: ${d.question_number}`);
      if (d.ai_interpretation) {
        lines.push("");
        lines.push(d.ai_interpretation);
      }
      break;
    }
    case "name": {
      const d = result.data;
      lines.push("Type: Name Reading");
      lines.push("");
      lines.push(`Name: ${d.name}`);
      lines.push(
        `Expression: ${d.expression} | Soul Urge: ${d.soul_urge} | Personality: ${d.personality}`,
      );
      if (d.ai_interpretation) {
        lines.push("");
        lines.push(d.ai_interpretation);
      }
      break;
    }
  }

  lines.push("");
  lines.push("— Generated by NPS Numerology Framework");
  return lines.join("\n");
}

export function ShareButton({ result }: ShareButtonProps) {
  const { t } = useTranslation();
  const [copied, setCopied] = useState(false);

  async function handleShare() {
    const text = generateShareText(result);
    try {
      await navigator.clipboard.writeText(text);
    } catch {
      // Fallback for insecure contexts
      const textarea = document.createElement("textarea");
      textarea.value = text;
      textarea.style.position = "fixed";
      textarea.style.opacity = "0";
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand("copy");
      document.body.removeChild(textarea);
    }
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  return (
    <button
      type="button"
      onClick={handleShare}
      className="share-button px-2 py-1 text-xs bg-nps-bg-input text-nps-text-dim hover:text-nps-text rounded transition-colors"
    >
      {copied ? t("oracle.copied") : t("oracle.share")}
    </button>
  );
}
